### PR TITLE
Support for API-only apps

### PR DESCRIPTION
**Pull request by felixandersen**
This is a PR as a base for further discussion. I am open for changes and feedback. This is more of a collection of changes I did to make the gem work for my situation. Hopefully it can be valuable upstream as well.

The gem currently does not work with API-only apps (http://edgeguides.rubyonrails.org/api_app.html). Since this is becoming more and more popular with Rails, I think it can be valuable to add support for this in the gem.

A few changes had to be made:

The use of a layout had to be removed. I do not see this as a great problem. The code is still DRY since the layout was only used in one place anyway.

I had to make the controllers inherit from ActionController::Base directly instead of ApplicationController from the host app. In a full stack Rails app ApplicationController always inherits from ActionController::Base, but in API-only apps it instead inherits from ActionController::API which does not provide logic for rendering html views.

I had to compile the css to a secondary file that gets used as a partial in case the app does not have an asset pipeline (this is the case with most API-only Rails app). This is very unorthodox and I am feeling a bit ill about it, but it is the only straight forward solution I could think of. The asset pipeline should still be used if available.

The host app needs to include the middleware Rack::MethodOverride since flipflop's html view uses the _method parameters when posting to do PATCH requests.

These changes also make flipflop's authentication through a method on ApplicationController not work. Lambda-style auth should still work though.

Let me know what you think. I am open to doing tweaks and further changes to make it ready for release if API-apps are an interesting target audience for you.

### CODE REVIEW

**Comment by rolftimmermans** [comment]
This is an excellent contribution. I'm all for supporting API only apps.

The CSS is a bit of a tricky situation. The released gem shouldn't have any dependencies on the asset pipeline.  So we probably want a better compilation step that is run on release. That might also address #11. The downside is that running the development version of flipflop (via a git URL in the Gemfile) may be more tricky and less obvious. Unless we also commit the compiled CSS to version control. But conceptually that doesn't really seem right.

Ideally I'd use the same solution for regular apps and API only apps. It's one less code branch to worry about.

I'd appreciate any input on how to address the CSS compilation that makes the released gem dependency-free, and the development version (via git) easy to use as well.

The change from `ApplicationController` to `ActionController::Base` may require a major version bump I think?

**Comment by felixandersen** [comment]
Great! I am sure we can find a solution that works in the end.

Regarding your point about the CSS. The released gem does indeed, contrary to your statement, at this moment, according to my testing, depend on the asset pipeline. This line: https://github.com/voormedia/flipflop/blob/f71b8a57cf91d69542f654a243136192a7afd732/lib/flipflop/engine.rb#L13 uses the assets-member on the config object that is only present if the assets pipeline is included in the host app. Did I misunderstand your wording? This was anyway what prompted me to do implement the changes. With the current conditional in place the asset-pipeline configuration is ignored on non asset-pipeline setups.

Committing the CSS is indeed the only straightforward way to ensure that users can run the gem from git URLs in their Gemfile. At least that I can think of.

If you are willing to compromise with that concept/rule and also go with the partial-view approach for including the style I think it is possible to completely remove the asset-pipeline dependency and ensure maximum compatibility with the fewest possible code paths/branches.

Yes, a major version bump with additional warnings/errors if the user tries to provide a symbol as the auth method is probably a good idea.

**Comment by rolftimmermans** [comment]
> The released gem shouldn't have any dependencies on the asset pipeline.

Well, with this I meant that I think it is not something that should be necessary, not that it currently doesn't. :) A bit confusing, sorry.

Maybe we just need to remove the SCSS file from `app`, move it to `src` or something, and provide a Rake task for compilation. Maybe not even automatically on release? We can just rely on the compiled CSS in git being correct. Any changes to the SCSS file would require recompilation. A bit harder for development maybe, but better for users.

**Comment by felixandersen** [comment]
Yep, I misunderstood then. You are right, it is a good ambition and would make it simpler to use in a API-only environment.

Your proposed solution is also a good one. I would say that the inconvenience in development is minimal and an acceptable tradeoff since the most actively developed part of the gem is not really the SCSS but the ruby-code.

Thoughts on how to proceed? Do you want me to change the code in this pull request to match our discussion? I will happily make changes after feedback later on as well. I guess you'd also want tests to pass?

**Comment by rolftimmermans** [comment]
It would be great if you can find a way to improve the situation with the CSS file! We definitely want the tests to pass in Travis, but the current errors would probably just go away if we don't use the asset pipeline anymore.

**Comment by felixandersen** [comment]
I have implemented what we discussed. I also added a few pointers to developers and users of the gem. Let me know what you think.

**Comment by felixandersen** [comment]
@rolftimmermans Have you had the time to look into the code? Any thoughts?

**Comment by rolftimmermans** [comment]
I have looked at the code and it looks good. There is one problem I see. The `ApplicationController` frequently includes helpers for authentication and such. I wonder what effect it would have to remove it from the inheritance chain. Any thoughts about that?

Also we need to fix the last test failure before we can merge.

**Pull request merged**
